### ISSUE TITLE
When the portal is built to run, Django should have appropriate permissions to access .venv/ on discover-dev.rc.nau.edu

### ISSUE THREAD

**Issue by 17jhagan** [DiscoverCCRI/portal_v1#23]
Issue to reflect the 'Second Build Django Error' on the Portal Issue Tracking document. 

This is a virtual environment dependency error specific to the RedHat VM that is hosting discover-dev.rc.nau.edu.

This error only occurs when it’s the second time running this instance of the portal. This issue has something to do with the Python virtual environment ‘venv’ and the pip requirements, specifically, the condition where all of the pip requirements are already installed

**Current Workaround (03/15):** With my current permissions on discover-dev.rc.nau.edu, I can move the .venv/ folder into another directory, like .old-venvs/, and start fresh with the dependencies on a given instance of the portal. This helps preserve current user data and experiments since I no longer need to switch to a clean directory and run a new install.

**Comment by nhatlinh300401** [comment]
Hi @17jhagan , does this error still happen in the RedHat VM ?

**Comment by 17jhagan** [comment]
Hi Linh, yes this error still happens on the RedHat VM. I believe it has to do with the permissions that are set when .venv is created (I believe Docker creates this, which I suspect is managed either by root or a special docker group). Check out the error message below:
```
aerpaw-portal  | created virtual environment CPython3.11.4.final.0-64 in 361ms
aerpaw-portal  |   creator CPython3Posix(dest=/code/.venv, clear=False, no_vcs_ignore=False, global=False)
aerpaw-portal  |   seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
aerpaw-portal  |     added seed packages: Django==4.2.2, asgiref==3.7.2, beautifulsoup4==4.12.2, certifi==2023.5.7, cffi==1.15.1, charset_normalizer==3.1.0, cryptography==41.0.1, django_bootstrap4==23.1, django_crispy_forms==2.0, django_fsm==2.8.1, idna==3.4, josepy==1.13.0, mozilla_django_oidc==3.0.0, multi_key_dict==2.0.3, pbr==5.11.1, pip==23.1.2, psycopg2_binary==2.9.6, pyOpenSSL==23.2.0, pycparser==2.21, python_dateutil==2.8.2, python_dotenv==1.0.0, python_jenkins==1.8.0, pytz==2023.3, requests==2.31.0, setuptools==67.8.0, six==1.16.0, soupsieve==2.4.1, sqlparse==0.4.4, uWSGI==2.0.21, urllib3==2.0.2, wheel==0.40.0
aerpaw-portal  |   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
aerpaw-portal  | Requirement already satisfied: pip in ./.venv/lib/python3.11/site-packages (23.1.2)
aerpaw-portal  | Obtaining aerpawgw-client from git+https://github.com/AERPAW-Platform-Control/aerpaw-gateway-client.git#egg=aerpawgw-client (from -r requirements.txt (line 11))
aerpaw-portal  | ERROR: Exception:
aerpaw-portal  | Traceback (most recent call last):
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/vcs/git.py", line 367, in get_remote_url
aerpaw-portal  |     found_remote = remotes[0]
aerpaw-portal  |                    ~~~~~~~^^^
aerpaw-portal  | IndexError: list index out of range
aerpaw-portal  | 
aerpaw-portal  | During handling of the above exception, another exception occurred:
aerpaw-portal  | 
aerpaw-portal  | Traceback (most recent call last):
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 169, in exc_logging_wrapper
aerpaw-portal  |     status = run_func(*args)
aerpaw-portal  |              ^^^^^^^^^^^^^^^
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 248, in wrapper
aerpaw-portal  |     return func(self, options, args)
aerpaw-portal  |            ^^^^^^^^^^^^^^^^^^^^^^^^^
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 377, in run
aerpaw-portal  |     requirement_set = resolver.resolve(
aerpaw-portal  |                       ^^^^^^^^^^^^^^^^^
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
aerpaw-portal  |     collected = self.factory.collect_root_requirements(root_reqs)
aerpaw-portal  |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
aerpaw-portal  |     req = self._make_requirement_from_install_req(
aerpaw-portal  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
aerpaw-portal  |     cand = self._make_candidate_from_link(
aerpaw-portal  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 185, in _make_candidate_from_link
aerpaw-portal  |     self._editable_candidate_cache[link] = EditableCandidate(
aerpaw-portal  |                                            ^^^^^^^^^^^^^^^^^^
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 318, in __init__
aerpaw-portal  |     super().__init__(
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 156, in __init__
aerpaw-portal  |     self.dist = self._prepare()
aerpaw-portal  |                 ^^^^^^^^^^^^^^^
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 225, in _prepare
aerpaw-portal  |     dist = self._prepare_distribution()
aerpaw-portal  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 328, in _prepare_distribution
aerpaw-portal  |     return self._factory.preparer.prepare_editable_requirement(self._ireq)
aerpaw-portal  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 683, in prepare_editable_requirement
aerpaw-portal  |     req.update_editable()
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 654, in update_editable
aerpaw-portal  |     vcs_backend.obtain(self.source_dir, url=hidden_url, verbosity=0)
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/vcs/versioncontrol.py", line 526, in obtain
aerpaw-portal  |     existing_url = self.get_remote_url(dest)
aerpaw-portal  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^
aerpaw-portal  |   File "/code/.venv/lib/python3.11/site-packages/pip/_internal/vcs/git.py", line 369, in get_remote_url
aerpaw-portal  |     raise RemoteNotFoundError
aerpaw-portal  | pip._internal.vcs.versioncontrol.RemoteNotFoundError
```

I believe the error occurs when trying to load detected dependencies from an old run into the current instance of the portal container. Then you start to see the index out of bounds error, likely because it ran into permission errors trying to pull the locally stored contents of the .venv/ folder, resulting in an empty set in the 'remotes' list.

When I move the current .venv/ folder into a different directory and rerun docker compose, the website boots up fine because it needs to recreate the virtual environment from scratch. I would just delete .venv/, but I don't have adequate permissions to do that.

**Comment by nhatlinh300401** [comment]
Since there's no errors in this issue, I will close it. If this error happens again, reopen the issue
